### ISSUE TITLE
Getting a cyclic dependency when trying to install kibana.

### ISSUE THREAD

**Issue by mrunkel** [elastic/puppet-kibana#18]
## Bug Report

* Module version: 6.0.0
* Puppet version: puppetserver version 5.1.4
* OS and version: Ubuntu 16.04.3 LTS

### Bug description

Expected behavior:
I'm expecting kibana to install.

Observed behavior:
I get an error about a cyclic dependency.

I have managed to successfully install logstash and elasticsearch on the same server..

Example manifest:

```puppet
  # install kibana

  class { 'kibana':
    config => {
      'server.host'       => $::role::elk::kibana_addr,
      'server.port'       => '5601',
      'elasticsearch.url' => "http://${::role::elk::elasticsearch_url}:${::role::elk::elasticsearch_port}",
    }
  }
```

Puppet run logs:
```
Error: Found 1 dependency cycle:
(Exec[apt_update] => Class[Apt::Update] => Package[apt-transport-https] => Exec[apt_update])
Cycle graph written to /opt/puppetlabs/puppet/cache/state/graphs/cycles.dot.
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph
```
![cycles](https://user-images.githubusercontent.com/3205232/33597186-e70e6016-d99e-11e7-9de6-7bb64f04aa2b.png)

**Comment by tylerjl** [comment]
@mrunkel I strongly suspect something else in your manifest may be to blame for the dependency cycle; as I cannot reproduce that same behavior. Also note that this module doesn't deal with the `apt-transport-https` and `ca-certificates` packages at all, so those nodes in the dependency cycle don't even apply to this module.

```
root@ubuntu-16-04:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
root@ubuntu-16-04:~# /opt/puppetlabs/bin/puppet --help | tail -n1
Puppet v4.10.9
root@ubuntu-16-04:~# systemctl is-active kibana
active
root@ubuntu-16-04:~# curl -I localhost:5601
HTTP/1.1 200 OK
kbn-name: kibana
kbn-version: 6.0.0
cache-control: no-cache
Date: Tue, 05 Dec 2017 16:33:27 GMT
Connection: keep-alive

root@ubuntu-16-04:~# cat test.pp
class { 'kibana' : }
root@ubuntu-16-04:~#
```

**Comment by mrunkel** [comment]
Hey @tylerjl I'll try a few more tests here.

I'm leaning in the same direction as you.  I'll see if I can install just kibana on a separate host with my "normal" manifests.

**Comment by mrunkel** [comment]
Further testing confirms that the problem lies elsewhere.   Sorry to waste your time.

**Comment by mrunkel** [comment]
I found the issue.

This error occurs when the elastic-stack, kibana and nginx modules are in the same manifest, so I think the problem is actually between elastic-stack and nginx.

Should I even be using elastic-stack?   I was using it to set the priority of the elastic repos, otherwise I get the old ubuntu versions instead.

**Comment by mrunkel** [comment]
Further investigations..

Ok. So I've disabled "manage_repo" for all modules and am now using elastic-stack to manage the repo.   The error still occurs.

I think it's this:

```puppet
      Class['apt::update'] -> Package <| |>
```

From /manifests/repo.pp in elastic_stack that is causing the problem.

**Comment by mrunkel** [comment]
Ok. I was able to solve this by simply defining the repo manually in hiera.

```YAML
apt::source:
  name: 'elastic'
  ensure: 'present'
  comment: 'Elastic package repository.'
  location: 'https://artifacts.elastic.co/packages/6.x'
  release: 'stable'
  repos: 'main'
  key:
    id: '46095ACC8548582C1A2699A9D27D666CD88E42B4'
    source: https://artifacts.elastic.co/GPG-KEY-elasticsearch'
  include:
    deb: true
    source: false
  pin: 510
```
